"""empty message

Revision ID: bc063c94d08e
Revises: 
Create Date: 2020-08-16 20:02:54.378081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc063c94d08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conn_speed_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload', sa.Float(precision='10,2'), nullable=False),
    sa.Column('download', sa.Float(precision='10,2'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('speed_unit', sa.Enum('mbps', name='speedunit'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conn_speed_tests')
    # ### end Alembic commands ###
